# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('imgurl', models.CharField(blank=True, max_length=255)),
                ('linkurl', models.CharField(blank=True, max_length=255)),
                ('parameter1', models.CharField(blank=True, max_length=255)),
                ('parameter1b', models.CharField(blank=True, max_length=255)),
                ('parameter2', models.CharField(blank=True, max_length=255)),
                ('parameter2b', models.CharField(blank=True, max_length=255)),
                ('parameter3', models.CharField(blank=True, max_length=255)),
                ('parameter3b', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Equip_table',
            },
        ),
        migrations.CreateModel(
            name='EquipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parameter1_disable', models.BooleanField(default=False)),
                ('parameter1_name', models.CharField(blank=True, max_length=255)),
                ('parameter1_type', models.CharField(blank=True, choices=[(b'0', b'numerical'), (b'1', b'enum'), (b'2', b'boolean'), (b'3', b'string')], max_length=255, null=True)),
                ('parameter1_note', models.CharField(blank=True, max_length=255)),
                ('parameter2_disable', models.BooleanField(default=False)),
                ('parameter2_name', models.CharField(blank=True, max_length=255)),
                ('parameter2_type', models.CharField(blank=True, choices=[(b'0', b'numerical'), (b'1', b'enum'), (b'2', b'boolean'), (b'3', b'string')], max_length=255, null=True)),
                ('parameter2_note', models.CharField(blank=True, max_length=255)),
                ('parameter3_disable', models.BooleanField(default=False)),
                ('parameter3_name', models.CharField(blank=True, max_length=255)),
                ('parameter3_type', models.CharField(blank=True, choices=[(b'0', b'numerical'), (b'1', b'enum'), (b'2', b'boolean'), (b'3', b'string')], max_length=255, null=True)),
                ('parameter3_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Type_table',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('finish', models.BooleanField(default=False)),
                ('eventType', models.CharField(choices=[(b'0', b'share'), (b'1', b'group'), (b'2', b'reserve')], max_length=20)),
                ('user_rate', models.IntegerField(default=-1)),
                ('user_note', models.TextField(blank=True)),
                ('manager_rate', models.IntegerField(default=-1)),
                ('manager_note', models.TextField(blank=True)),
                ('equip_rate', models.IntegerField(default=-1)),
                ('disable', models.BooleanField(default=False)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_equip', to='posts.Equip')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event_table',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'Lab_table',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='equip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_Type', to='posts.EquipType'),
        ),
        migrations.AddField(
            model_name='equip',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_equip', to='posts.Lab'),
        ),
    ]
