# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='equip_auth',
            field=models.ManyToManyField(blank=True, related_name='equip_auth', to='posts.Equip'),
        ),
        migrations.AddField(
            model_name='account',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_user', to='posts.Lab'),
        ),
    ]
